services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/financialApp
      - /financialApp/node_modules
    depends_on:
      - mongodb